// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdy2VOJhdQA9PFdZ_jQytI76k6VknGlGQ',
    appId: '1:610163437629:web:2419980db8969ff40d3a54',
    messagingSenderId: '610163437629',
    projectId: 'hospitalmanagementsystem-23681',
    authDomain: 'hospitalmanagementsystem-23681.firebaseapp.com',
    storageBucket: 'hospitalmanagementsystem-23681.firebasestorage.app',
    measurementId: 'G-BR8NYZC69R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFBPqD5HZJaIYMGbxXwHONVWgxsYC9c5M',
    appId: '1:610163437629:android:a573cfaed66407d50d3a54',
    messagingSenderId: '610163437629',
    projectId: 'hospitalmanagementsystem-23681',
    storageBucket: 'hospitalmanagementsystem-23681.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAf9NXm3RO1FlkuvueGhCoR4ICZKt66Go8',
    appId: '1:610163437629:ios:e6925a54955a714e0d3a54',
    messagingSenderId: '610163437629',
    projectId: 'hospitalmanagementsystem-23681',
    storageBucket: 'hospitalmanagementsystem-23681.firebasestorage.app',
    iosBundleId: 'com.example.hospitalmanagementsystem',
  );

}